name: decviz
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip
  
  # Node.js (npm comes bundled with Node.js)
  - nodejs=20.19.4
  
  # Essential development tools
  - git
  - curl
  - make
  - graphviz

# Environment variables
variables:
  NODE_ENV: development
  NEXT_TELEMETRY_DISABLED: 1
