name: decviz
channels:
  - conda-forge
  - defaults
dependencies:
  # Node.js (npm comes bundled with Node.js)
  - nodejs=20.19.4
  
  # Python and Logica
  - python=3.11
  - pip
  
  # Essential development tools
  - git
  - curl
  - make

# Pip dependencies
  - pip:
    - logica
    - pandas

# Environment variables
variables:
  NODE_ENV: development
  NEXT_TELEMETRY_DISABLED: 1
